/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '16. 5. 31 오후 10:04' with Gradle 2.12
 *
 * @author ggikko, @date 16. 5. 31 오후 10:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
